config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 root 'home#index'

  resources :genres, except: :destroy

  resources :animes do
    resources :characters
  end
  get 'top_favorite_animes', to: 'animes#top_favorite_animes', as: 'top_favorite_animes'

  resources :favorite_animes, only: [:index,:destroy]
  post 'favorite_animes/:anime_id', to: 'favorite_animes#create', as: 'add_favorite_anime'
end

app/models/anime.rb
class Anime < ApplicationRecord
  has_one_attached :image
  has_many :anime_genres, dependent: :destroy
  has_many :genres, through: :anime_genres, dependent: :destroy
  has_many :characters, dependent: :destroy
  has_many :favorite_animes, dependent: :destroy
  has_many :users, through: :favorite_animes
  validates :title, presence: true, length: {minimum: 5}
  validates :information, presence: true, length: { maximum: 200,
                                                    too_long: "%{count} characters is the maximum allowed" }
  validates :image, attached: true, content_type: [:png, :jpg],
            size: {less_than: 300.megabytes, message: "is not a given size"}
  paginates_per 6
end

app/models/anime_genre.rb
class AnimeGenre < ApplicationRecord
  belongs_to :anime
  belongs_to :genre
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  has_one_attached :avatar
  has_one_attached :image
  belongs_to :anime
  validates :character_name, presence: true, length: {minimum: 3}
  validates :character_description, presence: true, length: { maximum: 500,
                                                             too_long: "%{count} characters is the maximum allowed" }
  validates :appearance, presence: true, length: { maximum: 500,
                                                   too_long: "%{count} characters is the maximum allowed" }
  validates :role, presence: true
  validates :avatar, attached: true, content_type: [:png, :jpg]
  validates :image, attached: true, content_type: [:png, :jpg]
  paginates_per 6
end

app/models/favorite_anime.rb
class FavoriteAnime < ApplicationRecord

  belongs_to :user
  belongs_to :anime
  paginates_per 5
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :anime_genres, dependent: :destroy
  has_many :animes, through: :anime_genres, dependent: :destroy
  validates :genre_name, presence: true
  validates :content, presence: true
  paginates_per 6
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorite_animes, dependent: :destroy
  has_many :animes, through: :favorite_animes
  after_initialize :set_default_role, if: :new_record?

  def admin?
    self.role == "admin"
  end

  def reader?
    self.role == "reader"
  end

  private

    def set_default_role
      self.role ||= :reader
    end
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, only: [:new, :create]
  helper CharactersHelper

  def index
    @animes = Anime.includes(:genres).page(params[:page])
  end

  def show
    @anime = Anime.find(params[:id])
  end

  def new
    @anime = Anime.new
  end

  def create
    @anime = Anime.new(anime_params)
    @anime.image.attach(params[:anime][:image])
    if @anime.save
      flash[:success] = "Success! You have successfully created a new anime"
      redirect_to root_path
    else
      render :new
    end
  end

  def top_favorite_animes
    @top_favorite_animes = Anime.includes(:favorite_animes)
  end

  private

  def anime_params
    params.require(:anime).permit(:title, :information, genre_ids: [])
  end

  def admin_only
    unless current_user.admin?
      flash[:danger] = "Only admin can proceed to that action"
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def new
    @anime = Anime.find(params[:anime_id])
    @character = @anime.characters.new
  end

  def create
    @anime = Anime.find(params[:anime_id])
    @character = @anime.characters.build(character_params)
    @character.avatar.attach(params[:character][:avatar])
    @character.image.attach(params[:character][:image])
    if @character.save
      flash[:success] = "You have successfully inserted a new character"
      redirect_to anime_path(@anime)
    else
      render :new
    end
  end

  private

  def character_params
    params.require(:character).permit(:character_name,:character_description,:appearance,:role)
  end

end

app/controllers/favorite_animes_controller.rb
class FavoriteAnimesController < ApplicationController
  before_action :need_signed_in, only: [:create,:destroy]
  before_action :current_user_only, only: [:destroy]

  def index
    @favorites = current_user.admin? ? FavoriteAnime.includes(:anime,:user).page(params[:page]) : current_user.favorite_animes.includes(:user, :anime).page(params[:page])
  end

  def create
    @favorite = current_user.favorite_animes.build(anime_id: params[:anime_id])
    if @favorite.save
      flash[:success] = " #{@favorite.anime.title} is added to your favorites!"
      redirect_to animes_path
    else
      flash[:danger] = "Unable to add favorite anime."
      redirect_to animes_path
    end
  end

  def destroy
    @favorite = current_user.favorite_animes.find(params[:id])
    if @favorite.destroy
      flash[:success] = "#{@favorite.anime.title} is removed to your favorites!"
      redirect_to favorite_animes_path
    end
  end

  private

  def need_signed_in
    unless user_signed_in?
      flash[:danger] = "You need to signed in first to proceed in adding your favorite anime!"
      redirect_to animes_path
    end
  end

  def current_user_only
    unless current_user.id == @favorite.id
      flash[:danger] = "Only the reader can delete his own favorite anime!"
      redirect_to favorite_animes_path
    end
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  def index
    @genres = Genre.includes(:animes).page(params[:page])
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:success] = "Success! You have created a new genre"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:genre_name, :content)
  end

  def admin_only
    unless current_user.admin?
      flash[:danger] = "Only admin can delete a genre"
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper

  def main_character(characters)
    characters.where(role: "Main Character")
  end

  def side_character(characters)
    characters.where(role: "Side Character")
  end
end

app/helpers/favorite_animes_helper.rb
module FavoriteAnimesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/animes/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h2> Anime List </h2>
      <%= paginate @animes %>
      <div class="row>">
        <% @animes.each do |anime| %>
          <div class="col-sm-6 col-md-4">
            <div class="thumbnail thumbnail-index">
              <%= image_tag(anime.image, size: "300x300") %>
              <div class="caption">
                <h4><%= anime.title %></h4>
                <p><%= anime.information %></p>
                <p>
                  <a><%= link_to 'Show More', anime_path(anime), class: "btn btn-show-anime" %></a>
                  <% unless user_signed_in? && current_user.favorite_animes.exists?(anime_id: anime) %>
                    <%= link_to '<i class="glyphicon glyphicon-star"></i> Add to Favorites'.html_safe,
                                add_favorite_anime_path(anime), class: "btn btn-fav-anime",
                                method: :post, data: {confirm: "Are you sure?"} %>
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/animes/new.html.erb
<div class="container">
  <div class="row">
    <h2> Create Anime </h2>
    <%= render 'shared/errors', resource: @anime %>
    <div class="col-md-8 col-md-offset-2">
      <%= form_for @anime, url: animes_path(@anime), method: :post, html: {class: "form-horizontal form-genre", role: "form"} do |f| %>
        <div class="form-group">
          <%= f.label :title, class: "control-label col-sm-2" %>
          <div class="col-sm-10">
            <%= f.text_field :title, class: "form-control", placeholder: "Type name of genre..." %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :information, class: "control-label col-sm-2" %>
          <div class="col-sm-10">
            <%= f.text_area :information, class: "form-control", rows: 5, placeholder: "Content... " %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :Genres , class: "control-label col-sm-2"%>
          <div class ="col-sm-10">
            <div class="row">
              <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :genre_name do |checkbox| %>
                <% checkbox.label(class: "checkbox-inline input_checkbox") { checkbox.check_box(class: "checkbox") + checkbox.text } %>
              <% end %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :Thumbnail, class: "control-label col-sm-2"%>
          <div class ="col-sm-10">
            <%= f.file_field :image, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: "btn btn-create pull-right" %>
            <%= link_to "Back", root_path , class: "btn btn-default"%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/animes/show.html.erb
<div class="container">
  <div class="row">
    <h2 class="anime-header"> Anime </h2>
    <div class="anime">
      <div class="col-md-5 col-md-3">
        <div class="thumbnail">
          <%= image_tag(@anime.image, size: "400x400") %>
        </div>
      </div>
      <div class="anime-info">
        <p class="anime-title"> <%= @anime.title %>
          <% unless user_signed_in? && current_user.favorite_animes.exists?(anime_id: @anime.id) %>
            <%= link_to '<i class="glyphicon glyphicon-star"></i> Add to Favorites'.html_safe,
                        add_favorite_anime_path(@anime.id), class: "btn btn-fav-anime btn-sm",
                        method: :post, data: {confirm: "Are you sure?"} %>
          <% end %>
        </p>
        <p><strong><%= "Genre".pluralize(@anime.genres.count) %></strong>:
          <tr>
            <% @anime.genres.each do |genre| %>
              <td> <%= genre.genre_name %> </td>
            <% end %>
          </tr>
        </p>
        <p class="anime-summary"><strong>Summary:</strong> <%= @anime.information %></p>
      </div>
      <div class="anime-characters">
        <div class="row">
          <div class="col-md-12">
            <p class="character-header"> <%= "Character".pluralize(@anime.characters.size) %>
              <span class="badge badge-character"><%= @anime.characters.size %></span>
              <% if user_signed_in? && current_user.admin? %>
                <%= link_to "insert new character", new_anime_character_path(@anime), class: "btn btn-character" %>
              <% end %>
            </p>
            <%= render 'characters/index', characters: @anime.characters %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/animes/top_favorite_animes.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h2> Top Favorite Animes </h2>
      <table class="favorite_animes">
        <thead class="fav_anime_headers">
        <th witdh="50%">Anime</th>
        <th width="50%">Votes</th>
        </thead>
        <tbody>
        <% @top_favorite_animes.each do |anime| %>
          <tr class="fav_anime_datas">
            <td> <%= anime.title %> </td>
            <td> <%= anime.favorite_animes.size %></td>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/characters/_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <p class="main_character_header"> Main Character </p>
      <% maincharacter = main_character(characters) %>
      <% maincharacter.each do |character| %>
        <div class="row">
          <div class="col-md-4 col-md-offset-4">
            <div class="card">
              <%= image_tag(character.avatar, size: "75x75", class: "character_avatar") %>
              <p class="character_name"> <%= character.character_name %> </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-6">
      <% sidecharacter = side_character(characters) %>
      <p class="side_character_header"> <%= "Side Character".pluralize(sidecharacter.size) %></p>
      <% sidecharacter.each do |character| %>
        <div class="card">
          <%= image_tag(character.avatar, size: "75x75", class: "character_avatar") %>
          <p class="character_name"> <%= character.character_name %> </p>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">

  </div>
</div>

app/views/characters/new.html.erb
<div class="container">
  <div class="row">
    <h2> Insert a new character | Anime: <%= @anime.title %></h2>
    <%= render 'shared/errors', resource: @character %>
    <div class="col-md-10 col-md-offset-1">
      <%= form_for @character, url: anime_characters_path(@anime, @anime.characters.build), html: {class: "form-horizontal", role: "form"}, method: :post do |f| %>
        <div class="form-group">
          <%= f.label :Character_Name, class: "control-label col-sm-3" %>
          <div class="col-sm-9">
            <%= f.text_field :character_name, class: "form-control", placeholder: "character name..." %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :Character_Description, class: "control-label col-sm-3" %>
          <div class="col-sm-9">
            <%= f.text_area :character_description, rows: 5 ,class: "form-control", placeholder: "character description..." %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :Appearance, class: "control-label col-sm-3" %>
          <div class="col-sm-9">
            <%= f.text_area :appearance, rows: 5 ,class: "form-control", placeholder: "appearance..." %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :Role, class: "control-label col-sm-3" %>
          <div class="col-sm-8">
            <%= f.select :role, options_for_select(["Main Character", "Antagonist", "Side Character"], selected: "") %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :Avatar, class: "control-label col-sm-3"%>
          <div class ="col-sm-9">
            <%= f.file_field :avatar, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :Image, class: "control-label col-sm-3"%>
          <div class ="col-sm-9">
            <%= f.file_field :image, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: "btn btn-create pull-right" %>
            <%= link_to "Back", anime_path(@anime.id) , class: "btn btn-default"%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/favorite_animes/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h2> Favorite Animes </h2>
      <table class="favorite_animes">
        <thead class="fav_anime_headers">
        <th witdh="10%">ID</th>
        <% if current_user.admin? %>
          <th width="10%">Role</th>
          <th width="20%">Reader</th>
          <th width="30%">Anime</th>
          <th width="30%">Action</th>
        <% else %>
          <th width="60%">Anime</th>
          <th width="30%">Action</th>
        <% end %>
        </thead>
        <tbody>
        <% @favorites.each do |favorite| %>
          <tr class="fav_anime_datas">
            <td><%= favorite.id %></td>
            <% if current_user.admin? %>
              <td><%= favorite.user.role %></td>
              <td><%= favorite.user.email %></td>
            <% end %>
            <td><%= favorite.anime.title %></td>
            <td>
              <%= link_to 'Show', anime_path(favorite.anime), method: :get, class: "btn btn-show-anime btn-sm" %>
              <% if current_user.id == favorite.user.id %>
                <%= link_to 'Remove to Favorites', favorite_anime_path(favorite), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-remove-fav btn-sm" %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h2> All Genres </h2>
      <table class="favorite_animes">
        <tr class="fav_anime_headers">
          <th witdh="10%">ID</th>
          <th width="60%">Genre</th>
          <th width="30%">Action</th>
        </tr>
        <% @genres.each do |genre| %>
          <tr class="fav_anime_datas">
            <td><%= genre.id %></td>
            <td><%= genre.genre_name %></td>
            <td>
              <%= link_to 'Show', genre_path(genre), method: :get, class: "btn btn-show-anime btn-sm" %>
              <% if user_signed_in? && current_user.admin? %>
                <%= link_to 'Remove Genre', genre_path(genre), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-remove-fav btn-sm" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/genres/new.html.erb
<div class="container">
  <div class="row">
    <h2>Create Genre</h2>
    <%= render 'shared/errors', resource: @genre %>
    <div class="col-md-8 col-md-offset-2">
      <%= form_for @genre, url: genres_path(@genre), method: :post, html: {class: "form-horizontal form-genre", role: "form"} do |f| %>
        <div class="form-group">
          <%= f.label :genre_name, class: "control-label col-sm-2" %>
          <div class="col-sm-8">
            <%= f.text_field :genre_name, class: "form-control", placeholder: "Type name of genre..." %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :content, class: "control-label col-sm-2" %>
          <div class="col-sm-10">
            <%= f.text_area :content, class: "form-control", rows: 5, placeholder: "Content... " %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: "btn btn-create pull-right" %>
            <%= link_to "Back", root_path , class: "btn btn-default"%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <h2> Anime Haven!</h2>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="anime-footer">

  <div class="footer-copyright text-center py-3">© 2018 Copyright
    <p> Created by: Arnold Sulana</p>
  </div>


</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dissmiss="alert">&#215;</a>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span><%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse ">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Anime Haven', root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Anime Lists', animes_path %></li>
        <li><%= link_to 'Top Favorite Animes', top_favorite_animes_path %></li>
        <% if user_signed_in? && current_user.admin? %>
          <li><%= link_to 'Create Genre', new_genre_path %></li>
          <li><%= link_to 'Create Anime', new_anime_path %></li>
        <% end %>
        <% if user_signed_in? && (current_user.reader? || current_user.admin?) %>
          <li><%= link_to 'Favorites', favorite_animes_path %></li>
        <% end %>
        <li><%= link_to 'Genres', genres_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %>
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li> <%= link_to 'Log in', new_user_session_path, class: "btn btn-login btn-sm" %> </li>
          <li> <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-signup btn-sm" %> </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= I18n.t("errors.messages.not_saved",
                       count: resource.errors.count,
                       resource: resource.class.model_name.human.downcase)
            %>
          </h2>
        </div>
        <div class="panel-body">
          <ul>
            <% resource.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>